name: 'pre-Release Changelog Update'

on:
  workflow_call:
  release:
    types: [prereleased]

jobs:
  call-workflow-update-changelog:
    uses: figuren-theater/.github/.github/workflows/prerelease-changelog-update.yml@main
    secrets:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN || github.token }}

